require: rubocop-rails
AllCops:
  Exclude:
    - config/**/*
    - bin/*
    - node_modules/**/*
    - db/schema.rb

Style/FrozenStringLiteralComment:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Style/SymbolArray:
  Enabled: false